config/routes.rb
FastTrip::Application.routes.draw do
 

  match '/about',   to: 'static_pages#about'
  match '/contacts', to: 'static_pages#contacts'
  match '/help', to: 'static_pages#help'
  match '/terms', to: 'static_pages#terms'

  root to: 'trips#home'

  get "password_resets/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :trips

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete











end

app/models/trip.rb
class Trip < ActiveRecord::Base

  attr_accessible :content, :image, :title, :city, :country, :aviasalers_attributes, :hotelsalers_attributes, :hotels_attributes, :tickets_attributes, :no_visa
  has_many :aviasalers, :dependent => :destroy
  has_many :hotels, :dependent => :destroy
  has_many :tickets, :dependent => :destroy
  has_many :hotelsalers, :dependent => :destroy

  accepts_nested_attributes_for :aviasalers, :reject_if => lambda { |a| a.blank? }
  accepts_nested_attributes_for :hotels, :reject_if => lambda { |a| a.blank? }
  accepts_nested_attributes_for :tickets, :reject_if => lambda { |a| a.blank? }
  accepts_nested_attributes_for :hotelsalers, :reject_if => lambda { |a| a.blank? }
  validates :title, presence: true, length: { maximum: 34 }
  validates :image, presence: true
  validates :content, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :user_id, presence: true

  default_scope order: 'trips.created_at DESC'

  mount_uploader :image, ImageUploader


  def trip_sum
    @trip.aviasalers.sum(:price) + @trip.hotelsalers.sum(:price_one)
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
before_filter :admin_user, only: [:create, :destroy, :new, :edit, :update]


  def home
    @trips = Trip.all
  end

  def show
  	@trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
    @trip.aviasalers.build
    @trip.hotels.build
    @trip.tickets.build
    @trip.hotelsalers.build
  end

  def create
    @trip = current_user.trips.build(params[:trip])
    if @trip.save
      flash[:success] = "Trip created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    Trip.find(params[:id]).destroy
    flash[:success] = "deleted"
    redirect_to root_url
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update_attributes(params[:trip])
      flash[:success] = "Trip updated"
      redirect_to @trip
    else
      render 'edit'
    end
  end  
end

app/helpers/trips_helper.rb
module TripsHelper
	def trip_sum
		@price_there = @trip.aviasalers.select { |aviasaler| aviasaler.price if aviasaler.back_side == true }
		@price_back = @trip.aviasalers.select { |aviasaler| aviasaler.price if aviasaler.back_side == false }
		@hotel_four = @trip.hotelsalers.select { |hotelsaler| hotelsaler.price if telsaler.five_stars == false }
  	end
end

app/views/trips/_aviasaler_fields.html.erb
<fieldset>

  <%= link_to "remove", '#', class: "remove_fields" %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </p>

  <p>
    <%= f.label :actual_time %>
    <%= f.datetime_select :actual_time %>
  </p>

  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>

</fieldset>

app/views/trips/_aviasalers_fields.html.erb
<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :quantity %><br />
  <%= f.text_field :quantity %>
</p>

<p>
  <%= f.label :actual_time %><br />
  <%= f.datetime_select :actual_time %>
</p>

<p>
  <%= f.label :price %><br />
  <%= f.text_field :price %>
</p>

<p>
<%= f.check_box :_destroy %>
<%= f.label :_destroy, "Remove" %>
</p>

app/views/trips/_fields.html.erb
<div class="image_block">
  <%= f.label "Download the trip image" %><br>
  <%= f.file_field :image %>
</div>



<div class="trip_block">
  <div class="rounds left_trip"></div>
  <div class="rounds right_trip"></div> 
<div class="trip_block_border">
<div class="trip_part">
<p>
  <%= f.label "Trip name" %><br>
  <%= f.text_field :title, class:"trip_fields" %>
</p>

<p>
  <%= f.label "Trip description" %><br>
  <%= f.text_area :content, class:"trip_fields texter" %>
</p>

<p>
  <%= f.label :city %><br>
  <%= f.text_field :city, class:"trip_fields middle_trip_fields" %>
</p>

<p>
  <%= f.label :country %><br>
  <%= f.text_field :country, class:"trip_fields middle_trip_fields" %>
</p>
</div>
</div>

<div class="rounds left_trip"></div>
  <div class="rounds right_trip"></div>

<div class="trip_block_border">
<div class="trip_part">

  <%= f.label :no_visa %>
  <%= f.check_box :no_visa %>

</div>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_block_border">
<div class="trip_part">
 
<b>Flight there:</b>
<div class="sprite airplane_there"></div>
 
  <%= f.fields_for :tickets do |builder| %>
    <%= render 'ticket_fields', f: builder %>
    <%= builder.hidden_field :back_side, :value => false %>
  <% end %>

  <%= f.fields_for :aviasalers do |builder| %>
    <%= render 'salers_fields', f: builder %>
    <%= builder.hidden_field :back_side, :value => false %>
  <% end %>
</div>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_block_border">
<div class="trip_part">

<b>Flight back:</b>
<div class="sprite airplane_back"></div>

  <%= f.fields_for :aviasalers do |builder| %>
    <%= render 'salers_fields', f: builder %>
    <%= builder.hidden_field :back_side, :value => true %>
  <% end %>

  <%= f.fields_for :tickets do |builder| %>
    <%= render 'ticket_fields', f: builder %>
    <%= builder.hidden_field :back_side, :value => true %>
  <% end %>
</div>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_part">

<b>Hotel:</b>
<div class="sprite hotel_image"></div>


  <div class="sprite stars four_stars"></div>


  <%= f.fields_for :hotels do |builder| %>    
    <%= render 'hotels_fields', f: builder %>
    <%= builder.hidden_field :five_stars, :value => false %>
  <% end %>

  <%= f.fields_for :hotelsalers do |builder| %>    
    <%= render 'hotelsalers_fields', f: builder %>
    <%= builder.hidden_field :five_stars, :value => false %>
  <% end %>


  <p><div class="sprite stars five_stars"></div></p>
 <%= f.fields_for :hotels do |builder| %>    
    <%= render 'hotels_fields', f: builder %>
    <%= builder.hidden_field :five_stars, :value => true %>
  <% end %>

  <%= f.fields_for :hotelsalers do |builder| %>    
    <%= render 'hotelsalers_fields', f: builder %>
    <%= builder.hidden_field :five_stars, :value => true %>
  <% end %>

app/views/trips/_fields_edit.html.erb
<div class="image_block">
  <%= f.label "Download the trip image" %><br>
  <%= f.file_field :image %>
</div>



<div class="trip_block">
  <div class="rounds left_trip"></div>
  <div class="rounds right_trip"></div> 
<div class="trip_block_border">
<div class="trip_part">
<p>
  <%= f.label "Trip name" %><br>
  <%= f.text_field :title, class:"trip_fields" %>
</p>

<p>
  <%= f.label "Trip description" %><br>
  <%= f.text_area :content, class:"trip_fields texter" %>
</p>

<p>
  <%= f.label :city %><br>
  <%= f.text_field :city, class:"trip_fields middle_trip_fields" %>
</p>

<p>
  <%= f.label :country %><br>
  <%= f.text_field :country, class:"trip_fields middle_trip_fields" %>
</p>
</div>
</div>

<div class="rounds left_trip"></div>
  <div class="rounds right_trip"></div>

<div class="trip_block_border">
<div class="trip_part">

  <%= f.label :no_visa %>
  <%= f.check_box :no_visa %>

</div>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_block_border">
<div class="trip_part">
 
<b>Flight there:</b>
<div class="sprite airplane_there"></div>

  <%= f.fields_for :tickets, @trip.tickets.select{|ticket| ticket.back_side == false} do |ticket| %>
    <%= render 'ticket_fields', f: ticket %>
  <% end %>
 
  <%= f.fields_for :aviasalers, @trip.aviasalers.select{|aviasaler| aviasaler.back_side == false} do |aviasaler| %>
  <%= render 'salers_fields', f: aviasaler %>
  <% end %>

</div>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_block_border">
<div class="trip_part">

<b>Flight back:</b>
<div class="sprite airplane_back"></div>

  <%= f.fields_for :tickets, @trip.tickets.select{|ticket| ticket.back_side == true} do |ticket| %>
    <%= render 'ticket_fields', f: ticket %>
  <% end %>
 
  <%= f.fields_for :aviasalers, @trip.aviasalers.select{|aviasaler| aviasaler.back_side == true} do |aviasaler| %>
  <%= render 'salers_fields', f: aviasaler %>
  <% end %>

</div>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_part">

<b>Hotel:</b>
<div class="sprite hotel_image"></div>


  <div class="sprite stars four_stars"></div>

  <%= f.fields_for :hotels, @trip.hotels.select{|hotel| hotel.five_stars == false} do |hotel| %>    
    <%= render 'hotels_fields', f: hotel %>
  <% end %>

  <%= f.fields_for :hotelsalers, @trip.hotelsalers.select{|hotelsaler| hotelsaler.five_stars == false} do |hotelsaler| %>    
    <%= render 'hotelsalers_fields', f: hotelsaler %>
  <% end %>

  <p><div class="sprite stars five_stars"></div></p>

  <%= f.fields_for :hotels, @trip.hotels.select{|hotel| hotel.five_stars == true} do |hotel| %>    
    <%= render 'hotels_fields', f: hotel %>
  <% end %>

  <%= f.fields_for :hotelsalers, @trip.hotelsalers.select{|hotelsaler| hotelsaler.five_stars == true} do |hotelsaler| %>    
    <%= render 'hotelsalers_fields', f: hotelsaler %>
  <% end %>

app/views/trips/_hotels_fields.html.erb
<p>
    <%= f.label 'Hotel name'%><br>
    <%= f.text_field :name, class:"trip_fields" %>
</p>
<p>
    <%= f.label 'Hotel description' %><br>
    <%= f.text_area :description, class:"trip_fields texter" %>
    
</p>
<p>
    <%= f.label 'Hotel address' %><br>
    <%= f.text_field :address, class:"trip_fields" %>  
</p>

app/views/trips/_hotelsalers_fields.html.erb
<ul class="supplier">

<li>
 <%= f.label "Supplier" %><br>
 <%= f.text_field :name, class:"trip_fields middle_trip_fields" %>
<li>

<li>
 <%= f.label :quantity %><br>
 <%= f.text_field :quantity, class:"trip_fields small_trip_fields" %>
<li>

<li>
 <%= f.label :actual_time %><br>
 <%= f.datetime_select :actual_time, class:"trip_fields small_trip_fields" %>
<li>

<li>
 <%= f.label "Price single room($)" %><br>
 <%= f.text_field :price_one, class:"trip_fields middle_trip_fields" %>
</li>

<li>
 <%= f.label "Price double room($)" %><br>
 <%= f.text_field :price_two, class:"trip_fields middle_trip_fields" %>
</li>
<ul>

app/views/trips/_salers_fields.html.erb
<ul class="supplier">

<li>
 <%= f.label "Supplier" %><br>
 <%= f.text_field :name, class:"trip_fields middle_trip_fields" %>
<li>

<li>
 <%= f.label :quantity %><br>
 <%= f.text_field :quantity, class:"trip_fields small_trip_fields" %>
<li>

<li>
 <%= f.label :actual_time %><br>
 <%= f.datetime_select :actual_time, class:"trip_fields small_trip_fields" %>
<li>

<li>
 <%= f.label "Price ($)" %><br>
 <%= f.text_field :price, class:"trip_fields middle_trip_fields" %>
</li>
<ul>

app/views/trips/_ticket_fields.html.erb
<ul class="supplier">

<li>
    <%= f.label :departure_city %><br>
    <%= f.text_field :departure_city, class:"trip_fields middle_trip_fields" %>
</li>
<li>
    <%= f.label "Code" %><br>
    <%= f.text_field :departure_code, class:"trip_fields small_trip_fields" %>
</li>
<li>
    <%= f.label :departure_time %><br>
    <%= f.datetime_select :departure_time, class:"datetime" %>
</li>
<li>
    <%= f.label :arrival_city %><br>
    <%= f.text_field :arrival_city, class:"trip_fields middle_trip_fields" %>
</li>
<li>
    <%= f.label "Code" %><br>
    <%= f.text_field :arrival_code, class:"trip_fields small_trip_fields" %>
</li>
<li>
    <%= f.label :arrival_time %><br>
    <%= f.datetime_select :arrival_time, class:"trip_fields middle_trip_fields" %>
</li>


<li>
	<%= f.label :aviacompany %><br>
    <%= f.text_field :aviacompany, class:"trip_fields middle_trip_fields" %>
</li>
<li>
    <%= f.label :flight %><br>
    <%= f.text_field :flight, class:"trip_fields middle_trip_fields" %>
</li>
</ul>

app/views/trips/_trip.html.erb
<div class="block"> 
	<% if trip.no_visa? %>
	<div id="top_triangle"></div><div id="novisa"></div><div id="bot_triangle"></div>
	<% end %>
<div class="image">
<%= link_to image_tag(trip.image_url(:thumb).to_s), trip_path(trip.id) %> 
</div>
<div class="title_trip_left"><%= trip.title %></div>
<div class="dates_trip_left">
 <% for ticket in trip.tickets %>
      <% if ticket.back_side == false %>
        <%= ticket.departure_time.strftime("%B %d") %>
      <% elsif %>
      	-
      	<%= ticket.arrival_time.strftime("%B %d")  %>
      <% end %>
 <% end %>
</div>
<div class="places_trip_left"><%= trip.city %>, <%= trip.country %></div>
<div class="price">
<div id="price_p">
<%= number_to_currency(trip.aviasalers.sum(:price).to_i + trip.hotelsalers.where(five_stars:false).sum(:price_one),  precision: 0) %> 
</div></div>
<div class="line"><div class="rounds left"></div></div><div class="rounds right"></div> </div>

<!--
<% if current_user.try(:admin?) %>
<%= link_to "edit", edit_trip_path(trip.id), :class => 'action' %> 
| <%= link_to "delete", trip, method: :delete,
data: { confirm: "You sure?" },
title: trip.title %>
<% end %>
-->

app/views/trips/edit.html.erb
<% provide(:title, "Edit trip") %>
<h1>Edit trip</h1>

<%= form_for(@trip) do |f| %>
  <%= render 'fields_edit', f: f %>
  <%= f.submit "Save changes", id:"submit" %>
<% end %>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>
</div>
</div>

app/views/trips/home.html.erb
<% if current_user.try(:admin?)%>
<div id="trip_status">
<%= link_to "Create a trip", new_trip_path, id:"create_trips" %>
</div>
<% end %>

<ol class="trips">
  <%= render @trips %>
</ol>

app/views/trips/new.html.erb
<% provide(:title, 'Create a trip') %>
<h1>Trip details</h1>


  <%= form_for(@trip) do |f| %>
  	<%= render 'fields', f: f %>
  <%= f.submit "Create", id:"submit" %>
<% end %>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>
</div>
</div>

app/views/trips/show.html.erb
<div class="headliner"></div>

<div class="image_block2">

<div class="block_trip">
  <% if @trip.no_visa? %>
  <div id="top_triangle"></div><div id="novisa"></div><div id="bot_triangle"></div>
  <% end %>
<div class="image">
<%= link_to image_tag(@trip.image_url(:thumb).to_s), trip_path(@trip.id) %> 
</div>

<% if current_user.try(:admin?) %>
<div class="block_trip"> 
  <p>Tickets supplier there</p>
  <ul>
    <% for avisaler in @trip.aviasalers %>
      <% if avisaler.back_side == false %>
        <li><%= avisaler.name %></li>
        <li><%= avisaler.quantity %></li>
        <li><%= avisaler.price %></li>
        <li><%= avisaler.actual_time %></li>
      <% end %>
    <% end %>
  </ul>

  <p>Tickets supplier back</p>
  <ol>
    <% for avisaler in @trip.aviasalers %>
      <% if avisaler.back_side? %>
        <li><%= avisaler.name %></li>
        <li><%= avisaler.quantity %></li>
        <li><%= avisaler.price %></li>
        <li><%= avisaler.actual_time %></li>
      <% end %>
    <% end %>
  </ol>

 <p>Hotel supplier ****</p>
  <ul>
    <% for hotelsaler in @trip.hotelsalers %>
      <% if hotelsaler.five_stars == false %>
        <li><%= hotelsaler.name %></li>
        <li><%= hotelsaler.quantity %></li>
        <li><%= hotelsaler.price_one %></li>
        <li><%= hotelsaler.price_two %></li>
        <li><%= hotelsaler.actual_time %></li>
      <% end %>
    <% end %>
  </ul>

  <p>Hotel supplier *****</p>
  <ul>
    <% for hotelsaler in @trip.hotelsalers %>
      <% if hotelsaler.five_stars? %>
        <li><%= hotelsaler.name %></li>
        <li><%= hotelsaler.quantity %></li>
        <li><%= hotelsaler.price_one %></li>
        <li><%= hotelsaler.price_two %></li>
        <li><%= hotelsaler.actual_time %></li>
      <% end %>
    <% end %>
  </ul>
</div>
<% end %>

<div class="price">
<div id="price_p">
<%= number_to_currency(@trip.aviasalers.sum(:price).to_i + @trip.hotelsalers.where(five_stars:false).sum(:price_one),  precision: 0) %> 
</div></div>
<div class="line"><div class="rounds left"></div></div><div class="rounds right"></div> </div>
</div>



<div class="trip_block">
  <div class="rounds left_trip"></div>
  <div class="rounds right_trip"></div> 
<div class="trip_block_border">
<div class="trip_part">
  <div class="trip_block_border">
<h3><%= @trip.title %></h3>
  </div>
<p><%= @trip.city %></p> 
<p><%= @trip.country %></p> 

    <% for ticket in @trip.tickets %>
      <% if ticket.back_side == false %>
        <li><%= ticket.departure_time.strftime(" There at %B %d %t in %H:%M") %></li>
      <% elsif ticket.back_side == true %>
        <li><%= ticket.arrival_time.strftime("Back to Kyiv at %B %d %t in %H:%M") %></li>
      <% end %>
    <% end %>

<p><%= @trip.content %></p>
</div>
</div>

<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_block_border">
<div class="trip_part">
 
<div class="trip_block_border">
  <div class="sprite airplane_there"></div>
<h4>Flight there:</h4>

</div>
 
    <% for ticket in @trip.tickets %>
    <ul class="supplier">
      <% if ticket.back_side == false %>
      <p><b><%= ticket.departure_city %>(<%= ticket.departure_code %>) - <%= ticket.arrival_city %>(<%= ticket.arrival_code %>)</b></p>

        <li>Departure</br>
        <%= ticket.departure_time.strftime("%B %d %t") %></br>
        <%= ticket.departure_time.strftime("%H:%M") %>
        </li>

        <li>On the way</br>
        <%= ticket.aviacompany %>, <%= ticket.flight %></br>
        </li>

        <li>Arrival</br>
        <%= ticket.arrival_time.strftime("%B %d %t") %></br>
        <%= ticket.arrival_time.strftime("%H:%M") %>
          </li>
      <% end %>
    </ul>
    <% end %>

</div>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_part">

<b>Hotel in <%= @trip.city %></b>
<div class="sprite hotel_image"></div>


  <div class="sprite stars four_stars"></div>


    <% for hotel in @trip.hotels %>
      <% if hotel.five_stars == false %>     
        <li><%= hotel.name %></li>
        <li><%= hotel.description %></li>
        <li><%= hotel.address %></li>
      <% end %>
    <% end %>

  <p><div class="sprite stars five_stars"></div></p>

  <% for hotel in @trip.hotels %>
      <% if hotel.five_stars? %>       
        <li><%= hotel.name %></li>
        <li><%= hotel.description %></li>
        <li><%= hotel.address %></li>
      <% end %>
  <% end %>

</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>

<div class="trip_block_border">
<div class="trip_part">

<b>Flight back:</b>
<div class="sprite airplane_back"></div>

 
    <% for ticket in @trip.tickets %>
    <ul class="supplier">
      <% if ticket.back_side == true %>
      <p><b><%= ticket.departure_city %>(<%= ticket.departure_code %>) - <%= ticket.arrival_city %>(<%= ticket.arrival_code %>)</b></p>

        <li>Departure</br>
        <%= ticket.departure_time.strftime("%B %d %t") %></br>
        <%= ticket.departure_time.strftime("%H:%M") %>
        </li>

        <li>On the way</br>
        <%= ticket.aviacompany %>, <%= ticket.flight %></br>
        </li>

        <li>Arrival</br>
        <%= ticket.arrival_time.strftime("%B %d %t") %></br>
        <%= ticket.arrival_time.strftime("%H:%M") %>
          </li>
      <% end %>
    </ul>
    <% end %>

</div>

</div>
</div>
<div class="rounds left_trip"></div>
<div class="rounds right_trip"></div>
 <% if current_user.try(:admin?) %>
      <%= link_to "edit", edit_trip_path(@trip.id), :class => 'action' %> 
    | <%= link_to "delete", @trip, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: @trip.title %>
  <% end %>

</div>
</div>



  