config/routes.rb
FastTrip::Application.routes.draw do
 

  match '/about',   to: 'static_pages#about'
  match '/contacts', to: 'static_pages#contacts'
  match '/help', to: 'static_pages#help'
  match '/terms', to: 'static_pages#terms'

  root to: 'trips#home'

  get "password_resets/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :trips

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete











end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
    if user
  	  user.send_password_reset 
  	  redirect_to signin_url, :notice => "Email sent with password reset instructions."
    else
      flash.now[:error] = 'User with such email is not found'
      render 'new'
    end
  end

  def edit
  	@user = User.find_by_password_reset_token!(params[:id])
  end

  def update
  	@user = User.find_by_password_reset_token!(params[:id])
  	if @user.password_reset_sent_at < 2.hours.ago
    	redirect_to new_password_reset_path, :alert => "Password &crarr; 
      reset has expired."
  	elsif @user.update_attributes(params[:user])
    	redirect_to signin_url, :notice => "Password has been reset."
  	else
    	render :edit
  	end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div id="register"> 
    <p id="name_reg">Reset Password</p>
    <%= link_to "Sign in", signin_path, id: "enter_link" %>

    <%= f.password_field :password, placeholder: "Password", id: "input_fields" %>

    <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", id: "input_fields" %>
  </div>

  <div id="smb"><%= submit_tag("Update Password", id: "submit") %></div> 
<% end %>        
</div>

app/views/password_resets/new.html.erb
<div id="register"> 
    <p id="name_reg">Reset Password</p>
    <%= link_to "Sign in", signin_path, id: "enter_link" %>
    <%= form_tag password_resets_path, :method => :post do %>
    <%= text_field_tag :email, params[:email], placeholder: "E-mail", id: "input_fields" %>
    
    <div id="smb"><%= submit_tag("Reset Password", id: "submit") %></div> 
    <% end %>         
</div>