config/routes.rb
FastTrip::Application.routes.draw do
 

  match '/about',   to: 'static_pages#about'
  match '/contacts', to: 'static_pages#contacts'
  match '/help', to: 'static_pages#help'
  match '/terms', to: 'static_pages#terms'

  root to: 'trips#home'

  get "password_resets/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :trips

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete











end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         				:integer         not null, primary key
#  email      				:string(255)
#  password 				:string(minimum: 6)
#  password_confirmation 	:string
#  created_at 				:datetime
#  updated_at 				:datetime

class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  has_many :trips

  before_save { email.downcase! }
  before_save { create_secure_token(:remember_token) }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def send_password_reset
    create_secure_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(validate: false)
    UserMailer.password_reset(self).deliver
  end

  private

    def create_secure_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: [:index, :destroy]
  before_filter :signed_in_user_filter, only: [:new, :create]
  
  def show
    if current_user == User.find(params[:id])
      @user = User.find(params[:id])
    else
      redirect_back_or current_user
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    user_to_delete = User.find(params[:id]).destroy
    if (current_user == user_to_delete) && (current_user.admin?)
      flash[:error] = "Cannot delete own admin account!"
    else  
      user_to_delete.destroy
      flash[:success] = "User destroyed."
      redirect_to users_url
    end
  end


  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(signin_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb

<%= f.text_field :email, id: "input_fields", placeholder: "E-mail"%>

<%= f.password_field :password, id: "input_fields", placeholder: "Password"%>

<%= f.password_field :password_confirmation, id: "input_fields", placeholder: "Confirm password"%>

app/views/users/_user.html.erb
<li>
  <%= link_to user.email, user %>
  <% if user.admin? %>
  	| admin
  <% else %>
  	| user
  <% end %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', f: f %>
  <%= f.submit "Save changes" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul>
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<%= form_for(@user) do |f| %>
<div id="register"> 
	<p id="name_reg">Registration</p>
	<%= link_to "Sign in", signin_path, id: "enter_link" %>
	<%= render 'fields', f: f %>
	<div id="check">
		<label id="agreement">
			Agree with <a>user terms</a> and <a>private policy</a>
		</label>
	</div>
	<div id="smb"><%= f.submit "Create my account", id: "submit" %></div>
	<p id="remind"><%= link_to "Remind the password", new_password_reset_path %></p>
</div> 
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<h1><%= @user.email %></h1>