config/routes.rb
FastTrip::Application.routes.draw do
 

  match '/about',   to: 'static_pages#about'
  match '/contacts', to: 'static_pages#contacts'
  match '/help', to: 'static_pages#help'
  match '/terms', to: 'static_pages#terms'

  root to: 'trips#home'

  get "password_resets/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :trips

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete











end

app/views/layouts/_footer.html.erb
<footer>
<div id="foot_div">
<div id="footer720">
	<ul id="footer_nav">
  		<li><%= link_to "About", '#' %></li>
  		<li><%= link_to "Help", '#' %></li>
  		<li><%= link_to "Terms", '#' %></li>
 		<li><%= link_to "Privacy", '#' %></li>
 		<li><%= link_to "Contacts", '#' %></li>
	</ul>
 	<div id="details"> 2014 © fast trip — online travel store. 
The illustrations and all the information on this entire web site are the sole property of their authors.
To proceed you should be 18 or older. 
And don't forger your visa.</br>
<p id="greeting"><b>Have a nice trip!</b></p>

	</div>


<div class="footertext">
hello@fasttrip.me | +38 093 064 94 14 | +38 096 229 64 77 | +38 093 221 13 51
</div>
</div>

<ul class="right_nav_footer">
	<li class="sprite payment"></li>
	<li>flat project</li>
	<li class="sprite social"></li>
</ul>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="user_header">
    <div id= "header_div">
    <li>hello@fasttrip.me | +38 093 063 94 14</li>  
    
    <nav>

      <%= render 'layouts/right_nav' %>
    </nav>
  </div>
</header>   

<% if current_page?(root_path) %>   
<div class="cover">
   
<div id="big">
   <div class="calculator"> 
      <div id="trip">
       <div id="fast_trip_big"></div>
       <div id="logo_big"></div>
       <div id="elipse_big"></div>  
       <div id="from">from Kyiv</div>

       <div id="qq" class="dd wrapper-dropdown-3"><span>one person</span>
        <ul class="dropdown">
            <li><a href="#">one person</a>
            </li>
            <li><a href="#">2 persons</a>
            </li>
            <li><a href="#">3 persons</a>
            </li>
            <li><a href="#">4 persons</a>
            </li>
        </ul>
       </div>
        
       <div id="dd" class="wrapper-dropdown-3"><span>one room</span>
        <ul class="dropdown">
            <li><a href="#">one room</a>
            </li>
            <li><a href="#">2 rooms</a>
            </li>
            <li><a href="#">3 rooms</a>
            </li>
            <li><a href="#">4 rooms</a>
            </li>
        </ul>
       </div>  
      </div>   
   </div>
</div>
</div>      
 <% end %>  

app/views/layouts/_header_admin.html.erb
<header>
  <div id= "header_div">
    <div class="head_ticket">
      <%= link_to " ", root_path, id:"fast_trip" %>
      <div id="logo"></div>
      <div id="elipse"></div>  
    </div>
    
    <nav>
      <div class="admin_buttons">
        <ul class="buttons_header">  
          <li><%= link_to "Users", '#' %></li>  
          <li><%= link_to "Orders", '#' %></li> 
          <li><%= link_to "Trips", '#' %></li> 
        </ul>
      </div>
      <%= render 'layouts/right_nav' %>
    </nav>

    </div>
</header>


            

app/views/layouts/_right_nav.html.erb
<ul class="name">       
  <li>English</li>
  <li>USD</li>
  <% if signed_in? %>
  <li class="signin"><%= link_to "Account", '#' %></li>
    <ul class="acc_menu">
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li> 
      <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
    </ul>
  <% else %>    
  <li class="signin"><%= link_to "Sign in", signin_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="content">
        
      <% if current_user.try(:admin?) %>
        <%= render 'layouts/header_admin' %>
      <% else %>
        <%= render 'layouts/header' %>
      <% end %>


      <div class="contentwrapper">
      <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
        <%= yield %>
      </div>

      <div class="clearfooter"></div>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>